# Generated by Django 3.0.4 on 2020-03-21 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
