# Generated by Django 3.0.4 on 2020-03-21 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_nlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('dad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nlist')),
            ],
        ),
    ]
