# Generated by Django 3.0.4 on 2020-03-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dad',
            field=models.IntegerField(),
        ),
    ]
