# Generated by Django 3.0.4 on 2020-03-30 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200321_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='des',
            field=models.TextField(default='None'),
        ),
    ]
