# Generated by Django 3.0.4 on 2020-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200330_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
